apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-git-clone
    labels:
        app: go-git-clone
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-git-clone
    template:
        metadata:
            labels:
                app: go-git-clone
        spec:
            containers:
                - name: go-git-clone
                  image: amitkrdas/go-git-clone:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: my-service
spec:
    type: NodePort
    selector:
        app: go-git-clone
    ports:
        # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
        - port: 80
          targetPort: 3000
